config/routes.rb
Rails.application.routes.draw do
  get 'images/create'
  devise_for :users
  root to: 'events#index'

  resources :events do
      resources :images, only: [:create]
  end
  
  scope 'superadmin', module:'admin', as: 'admin' do
   resources :events
  end

  resources :users
  resources :attendances
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord

  #after_create :attendance_email

  belongs_to :participant, class_name: "User"
  belongs_to :event

  #def attendance_email
  #  AttendanceMailer.attendant_email(self).deliver_now
  #end
end

app/models/event.rb
class Event < ApplicationRecord

  # Associations

  has_many :attendances
  has_many :participants, class_name: "User", through: :attendances
  belongs_to :admin, class_name: "User"
  has_one_attached :image



  # Validations 
  
  validates :start_date, 
  presence: true, 
  if: :not_past_date #-> La date ne peut pas être dans le passé

  validates :duration, 
  presence: true,
  numericality: { only_integer: true },
  if: :modulo_5 #-> La durée doit être un multiple de 5
  
  validates :title,
  presence: true,
  length: {in: 5..140} #-> Le titre à entre 5 et 140 caractères

  validates :description,
  presence: true,
  length: {in: 20..1000} #-> La description à entre 20 et 1000 caractères

  validates :price, 
  presence: true,
  numericality: { only_integer: true }, 
  :inclusion => 1..1000 #-> Le prix doit être un integer entre 1 et 1000

  validates :location, 
  presence: true



  # Méthodes de validations

private

  def modulo_5
    if duration.present? && duration % 5 == 0
      return true
    else
      errors.add(:duration, 'Un multiple de 5 only please')
    end
  end

  def not_past_date
    if self.start_date.present? && self.start_date < DateTime.now
      errors.add(:date, 'Pas une date passée')
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  #after_create :welcome_send #-> Envoie un mail après la création d'un user

  has_many :attendances
  has_many :events, through: :attendances
  has_many :events

  #def welcome_send
  #  UserMailer.welcome_email(self).deliver_now
  #end
end

app/controllers/admin/application_controller.rb
module Admin
  
  class ApplicationController < ::ApplicationController
    #layout 'admin'

    before_action :only_admin

    private

    def only_admin
      if current_user.nil?
        flash[:danger] = "ouaiiiis bah non.."
        redirect_to root_path
      end
    end
  end

end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < ApplicationController

    def index
      @event = Event.all
    end

    def new
      @event = Event.new
    end

    def create
    end

    def edit
    end

    def destroy
    end


  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_paramaters, if: :devise_controller?

  def configure_devise_paramaters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :first_name, :last_name, :description, :password, :password_confirmation) }
  end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  
  def index
    @event = params[:event_id]
  end

  def new

  end

  def create

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = params[:event_id]
    @event_price = Event.find(@event).price
    @event_name = Event.find(@event).title

    $event = @event
    #->Désolé pour la variable globale...
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    if @new_attendance = Attendance.create(participant_id: current_user.id, event_id: $event, stripe_customer_id: params['stripeToken'])
      redirect_to event_path($event)
    else
      redirect_to new_charge_path
    end

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [ :edit, :new]

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @participants = Attendance.where(event_id: @event.id)
    @admin_of_event = @event.admin
    @date_end = @event.start_date + @event.duration
    if current_user.nil? == false
      @participant_current = Attendance.where(event_id: @event.id).find_by(participant_id: current_user.id)
      @button_condition = @participant_current.nil? && current_user != @event.admin
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    if @event.update(start_date: params['start_date'], duration: params['duration'], title: params['title'], description: params['description'], price: params['price'], location: params['location'])
    redirect_to root_path
    else
      render :new
    end
  end
    

  def new
  end

  def create
    @new_event = Event.new(start_date: params['start_date'], duration: params['duration'], title: params['title'], description: params['description'], price: params['price'], location: params['location'], admin_id: current_user.id)

    if @new_event.save
      redirect_to root_path
    else
      redirect_to new_event_path
    end

  end

  def destroy
    @event = Event.find(params[:id])

    if @event.destroy
      redirect_to root_path
    else
      render :new
    end
  end

end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def create
    @event = Event.find(params[:event_id])
    @event.image.attach(params[:image])
    redirect_to (event_path(@event))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!,
  only: [:show]
 
   def show
    @user = User.find(params[:id])
    @event_create = Event.where(admin_id: @user)
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_Admin?
    user_signed_in? && current_user.role == "admin"
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admin/events/index.html.erb
<h1>Gerer les events</h1>

<table class="table table-striped">
<thread>
<tr>
	<th>Date</th>
	<th>Titre</th>
	<th>Prix</th>
	<th>Lieux</th>
	<th>Editer/Supprimer</th>
</tr>
</thread>
<tbody>

<% @event.each do |event| %>
	<tr>
		<td><%= event.start_date %></td>
		<td><%= event.title %></td>
		<td><%= event.price %></td>
		<td><%= event.location %></td>
	<td>
		<%=link_to "Editer Event", edit_event_path(event), class:"btn btn-primary my-2"%>
		<%= form_tag event_path(event), method: "delete", style: "display: inline" do %>
		<%= submit_tag "Supprimer l'event", class:"btn btn-light" %>
		<% end %>
	</td>
	</tr>
<%end%>
</tbody>

app/views/attendances/index.html.erb
<p class="text-center">
	<h3>Voici les participants de ton évènement :</h3>
<% Attendance.where(event_id: @event).each do |attendance| %>
	<p><%= User.find(attendance.participant_id).email %></p>
<% end %>

<%=link_to "Editer Event", edit_event_path(@event), class:"btn btn-primary my-2"%>

<%= form_tag event_path(@event), method: "delete", style: "display: inline" do %>
<%= submit_tag "Supprime ton event", class:"btn btn-light" %>
<% end %>

app/views/attendances/new.html.erb
<html>
<body> 
	<div class="container col-md-8 order-md-1">
		<div class="form-group"><br><br>
			<h3> Dernière étape </h3>
			<p> Détails : </p>
			<p><b> Nom de l'event : <%= @event_name %> </b></p>
			<p><b> Prix : <%= @event_price %> € </b></p>
	<%= form_tag url_for(action: 'create'), method: "post" do %>
	<%= label_tag 'Ajouter votre compte stripe' %>
	<%= text_field_tag 'stripe', @stripe, class:'form-control' %> <br /> 

	<%= submit_tag "Finaliser l'inscription", class:"btn btn-light" %> <% end %>

</div>
</body> 
</html>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
    	<p>Maintenant il faut payer !</p>
    	<p>Pour l'evenement : <%= @event_name %> </p>
      <span>Montant : <%= @event_price %> €</span>
    </label>
  </article>


</div>
</body> 
</html>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount= <%= @event_price*100 %>
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<html> 

<body> 
	<!-- ... --> 
	<div class="container col-md-8 order-md-1">
		<div class="form-group"><br><br>
			<h3> Edite ton event ! </h3>
 <br />
	<%= form_tag url_for(action: 'update'), method: "patch" do %> 
	<%= label_tag 'Date de début' %> 
	<%= text_field_tag 'start_date', @event.start_date, class:'form-control' %> <br /> 

	<%= label_tag 'Durée' %> 
	<%= text_field_tag 'duration', @event.duration, class:'form-control' %> <br /> 

	<%= label_tag 'Titre' %> 
	<%= text_field_tag 'title', @event.title, class:'form-control' %> <br /> 

	<%= label_tag 'Description' %> 
	<%= text_area_tag 'description', @event.description, class:'form-control' %> <br />

	<%= label_tag 'Prix' %> 
	<%= text_field_tag 'price', @event.price, class:'form-control' %> <br /> 


	<%= label_tag 'Lieu'%> 
	<%= text_field_tag 'location', @event.location, class:'form-control' %> <br />

	<%= submit_tag "Mets à jour ton event", class:"btn btn-light" %> <% end %>

</div>
</body> 
</html>

app/views/events/index.html.erb
<style>
.card{margin: 1%}
.contain{margin-left: 10%;margin-right: 10%; background-color: }
</style>

<!-- Light caption -->
<div class="contain">
<div class="d-flex align-content-between flex-wrap">
	<% Event.all.each do |event| %>
		<div class="card" style="width: 30rem;">
		    <div class="card-image">
		    	<a href="/events/"><% event.id %>
		            <img src="https://media.giphy.com/media/4oMoIbIQrvCjm/giphy.gif">
		        </a>
		    </div>
		    <div class="card-caption-overlay card-caption-overlay--3">
		        <div class="card-caption">
		            <div class="text-center">
		                <%=event.title %>
		                </a>
		                <span class="clearfix"></span>
		                <span class="text-sm"><%= event.description%></span><br><br>
		                <div class="text-center"><%= link_to "Participer", event_path(event.id), class:"btn btn-base-2"%></div>
		            </div>
		        </div>
		    </div>
		</div>
	<% end %>
</div>
</div>

app/views/events/new.html.erb
<html> 
<body> 
	<!-- ... --> 
	<div class="container col-md-8 order-md-1">
		<div class="form-group"><br><br>
			<h3> Créé ton event ! </h3>
 <br />
	<%= form_tag url_for(action: 'create'), method: "post" do %> 
	<%= label_tag 'Date de début' %> 
	<%= text_field_tag 'start_date', @start_date, class:'form-control' %> <br /> 

	<%= label_tag 'Durée' %> 
	<%= text_field_tag 'duration', @duration, class:'form-control' %> <br /> 

	<%= label_tag 'Titre' %> 
	<%= text_field_tag 'title', @title, class:'form-control' %> <br /> 

	<%= label_tag 'Description' %> 
	<%= text_area_tag 'description', @description, class:'form-control' %> <br />

	<%= label_tag 'Prix' %> 
	<%= text_field_tag 'price', @price, class:'form-control' %> <br /> 


	<%= label_tag 'Lieu'%> 
	<%= text_field_tag 'location', @location, class:'form-control' %> <br />

	<%= submit_tag "Créé ton event !", class:"btn btn-light" %> <% end %>

</div>
</body> 
</html>

app/views/events/show.html.erb
<div class="row row-no-gutters">
  <div class="col-sm-3">




 <% if @event.image.attached? %>
<%= image_tag @event.image, alt:'image',width: 250 %>
<%end%>
<% if %>
	<%= form_tag event_images_path(@event), multipart: true do %>
	<%= file_field_tag :image %>
	<%= submit_tag "mettre à jour", class:"btn btn-primary my-2" %>
<%end%>
<% end %>

<% if @button_condition %>
		<%=link_to "Rejoindre l'event", {:controller => "charges", :action => "new", :event_id => @event.id} , class:"btn btn-base-2 my-2"%>
		<% end %>

<% if @admin_of_event == current_user %>
<%=link_to "Mon espace événement",{:controller => "attendances", :action => "index", :event_id => @event.id} , class:"btn btn-primary my-2"%>
<% end %>				
</div>





  <div class="col-sm-6"> 
		<h1 class="jumbotron-heading"><%= @event.title %></h1><br><br>
		<p><b><%= @event.description %></b></p><br>
		<p>Créateur de l'evenement :<b> <%= @admin_of_event.email %></b>
		<p>Nombre de participants : <b><%= @participants.count %></b></p><br><br>
		<p>Lieu : <b><%= @event.location %></b></p>
		<br><br><p>Date de début : <b><%= @event.start_date %></b></p>
		<p>Date de fin : <b><%= @date_end %></b></p></div>
  <div class="col-sm-3"></div>
</div>


	</div>
</section>

app/views/images/create.html.erb
<h1>Images#create</h1>
<p>Find me in app/views/images/create.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<style>
.card{margin: 1%}
</style>

<!-- Si ce n'est pas la page du current User, il ne peut pas voir cette page -->
<% if current_user == @user %>

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">
      <% if @user.first_name.nil? %>
        Hey user<%= @user.id %> !
        <% else %>
        Hey <%= @user.first_name %> !</h1>    
      <% end %><br>
    <%= link_to 'Edit Profile', edit_user_registration_path, class:"btn btn-primary my-2" %>
  </div>
</section>

<h3 class="text-center">Voici les events que tu as créés :</h3><br>
<div class="d-flex align-content-between flex-wrap">
  <% @event_create.each do |event| %>
  <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="https://media.giphy.com/media/3o7bue1I6RarmeDjW0/giphy.gif" alt="Card image cap">
    <div class="card-body">
      <h5 class="card-title"><%= event.title %></h5>
      <p class="card-text"><%= event.description%></p>
      <%= link_to "Voir l'event", event_path(event.id), class:"btn btn-primary" %>
    </div>
  </div>
  <% end %>
</div>




<!-- Si ce n'est pas la page du current User, il ne peut pas voir cette page -->
<% else %>

<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading"><h1> Vous n'avez pas accès à cette page </h1>
  </div>
</section>

<% end %>